# Build and push image

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      appName:
        description: 'app name for image tag name' 
        required: true
      ecrRepository:
        description: 'ECR repository name where image will be deployed to'     
        required: true
      AWS_ACCESS_KEY_ID:
        description: 'AWS_ACCESS_KEY_ID'     
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS_SECRET_ACCESS_KEY'     
        required: true
      AWS_SESSION_TOKEN:
        description: 'AWS_SESSION_TOKEN'     
        required: true

name: Elixir CI

jobs:

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: philips-software/sonar-scanner-action@<version>
        with:
          token: ${{ secrets.SONARQUBE_TOKEN }}
          projectName: Oracle Service
          projectKey: project.key.from.sonar.qube
          url: http://ec2-54-242-150-198.compute-1.amazonaws.com:9000/
          isCommunityEdition: true

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.13' # Define the elixir version [required]
          otp-version: '25' # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test

#      - name: Configure AWS credentials
#        id: creds
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
#          aws-session-token: ${{ github.event.inputs.AWS_SESSION_TOKEN }}
#          aws-region: us-east-1
      
#      - name: Login to Amazon ECR
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v1

#      - name: Build, tag, and push image to Amazon ECR
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#          ECR_REPOSITORY: ${{ github.event.inputs.ecrRepository }}
#          IMAGE_TAG: ${{ github.event.inputs.appName }}_v${{ github.run_number }}
#        run: |
#          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG



